% function p1 = sec10(uid, eid, did, p1suff, opt, pathraw0, pathdata0, pathrepo0, pathtemp0)
disp("SECTION 10 RUNNING ...");

comInit;

% parallel
%   we may not parallel for this process of Heidenberg data
% SetParPool(8);  

%%%% p1: struct to save all data collection information and processing parameters

% basic
p1 = struct;
p1.uid = uid;
p1.eid = eid;
p1.did = did;
p1.p1suff = p1suff;
p1.id = sprintf("%s-%s", did, p1suff);

% folders
%   Processed data usually do not have uid. 
%   But they have hypothesis folder, since different hypotheses often require different data.
%       When we need to analyze the same data across different hypotheses, we can specify the hypothesis folder.
%       For instance, in adp-3, Kuan works on the hypothesis B-e2e, but needs data generated by app1 of the 
%       hypothesis A-segment. In this case, we can specify the hypothesis folder A-segment in the data path.
%   Report figures usually put all figures from the hypothesis level in the same folder to use filtering later. 
%       The report figures have eid and p1.id tags in their file name, facilitating the later filtering when needed.
%       More tags will be added for each report figures.
p1.pathraw = sprintf("%s/%s/%s", pathraw0, uid, eid);
p1.pathdata = sprintf("%s/%s", pathdata0, eid);  
p1.pathrepo = sprintf("%s/1-reconstruct #%s #%s", pathrepo0, p1.eid, p1.id);
p1.pathtemp = sprintf("%s/%s/%s", pathtemp0, uid, eid);
if isempty(dir(p1.pathdata))
    mkdir(p1.pathdata);
end
if isempty(dir(p1.pathtemp))
    mkdir(p1.pathtemp);
end

%%%% p1.opt

opt = struct;
switch p1suff
    case "p1a"
        % default opt
        opt.snr = 0;
        opt.snrAng = 0;
            % snr = 0 : SNR for log preview of OCT. 0 means no log. 1e2 is OK.
            % snrAng = 0 : SNR for log preview of OCTA. 0 means no log. 1e2 is OK.
        opt.zAboveIlm = 20;
            % In making the first layer (above ILM) in r1.lyr, how many 
            % voxels above ILM will be included. 0 means "include all 
            % voxels". Including only a subset of voxels produced a better
            % en face MIP of OCTA of the top layer, as it excludes noise 
            % from the top of B-scans (autocorrelation noise?).
        opt.zBelowRpe = 40;
            % In making the last layer (below RPE) in r1.lyr, how many
            % voxels below RPE will be included. 0 means "include all
            % voxels". Including only a subset of voxels produced a better
            % en face MIP of OCTA of the last layer, as it excludes noise 
            % from the bottom of B-scans.
        opt.lyrComb = [2 6; 8 8; Inf Inf];
            % Representative combinations of layers in fig
            % #12-ang-layer-comb. Inf means the last layer (for case layer
            % number differs between data).
            %   #12-seg-ang showed surface vessels elongated across layers 2-6, and
            %   distinct smaller vessels in layer 8.  The last layer (below RPE) also
            %   showed some new vessels.
    otherwise
        error("Not supported p1suff: %s", p1suff);
end
p1.opt = opt;  % processing options given by the user (identified by p1suff)

% print p1 for check
p1
p1.opt

% Check if p1id file exists
fpath = sprintf("%s/%s.mat", p1.pathdata, p1.id);
if ~isempty(dir(fpath))
    error("Processed data already exists. Rename p1suff or delete the existing file. It is not recommended to rename the existing file:\n%s", ...
        fpath);
end

disp("SECTION10 COMPLETED.");
